name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Lint:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check tool versions
        run: |
          rokit --version
          luau-lsp --version
          rojo --version
          stylua --version

      - name: Generate sourcemap
        run: rojo sourcemap --output sourcemap.json --include-non-scripts

      - name: Analyze
        run: curl -sO https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.luau && luau-lsp analyze --defs=globalTypes.d.luau --sourcemap sourcemap.json src/ test/ && rm globalTypes.d.luau

      - name: Format
        run: stylua --check src/ test/

  Test:
    environment: testing
    runs-on: ubuntu-latest
    concurrency:
      group: luau-execution
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: "*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run tests
        run: set -e && rojo build ./test/default.project.json --output dist.rbxl && python3 ./test/upload_and_run_task.py dist.rbxl $TEST_TASK_FILE && rm dist.rbxl
        env:
          ROBLOX_API_KEY: ${{ secrets.ROBLOX_API_KEY }}
          ROBLOX_UNIVERSE_ID: ${{ secrets.ROBLOX_TEST_UNIVERSE_ID }}
          ROBLOX_PLACE_ID: ${{ secrets.ROBLOX_TEST_PLACE_ID }}
          TEST_TASK_FILE: test/task.luau
